language: emacs-lisp
sudo: required

cache:
  - directories:
      # Cache stable Emacs binaries
      - "$HOME/emacs/"
env:
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1

before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask

install:
  - make elpa

script:
  - make test
